services:
  - type: web
    name: express-server
    env: node
    buildCommand: "pnpm install"
    startCommand: "node index.js"
    plan: free

  - type: worker
    name: express-worker
    env: node
    buildCommand: "pnpm install"
    startCommand: "node worker.js"
    plan: free
